#!/usr/bin/env python3
"""
rebuild_indexes.py
Auto-génère / met à jour les index "source de vérité" d'un repo root_IA.

Génère (par défaut en mode sûr) :
- 10_TEAMS/teams.yaml
- 50_POLICIES/POLICIES__INDEX.md
- 00_INDEX/agents.yaml (inventaire)
- agent.yaml manquants sous 20_AGENTS/**/
- (optionnel) bundles 90_KNOWLEDGE/* (si --bundles)

Mode sûr :
- Si un fichier cible existe déjà et ne contient pas le marqueur "AUTO-GENERATED",
  le script n'écrase pas : il écrit plutôt un fichier .new et affiche un avertissement.

Usage:
  python scripts/rebuild_indexes.py
  python scripts/rebuild_indexes.py --root "C:\\path\\to\\root_IA" --force --bundles
"""

from __future__ import annotations

import argparse
import datetime as _dt
import os
import re
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

AUTO_MARKER = "AUTO-GENERATED by scripts/rebuild_indexes.py"

def _now_iso() -> str:
    return _dt.datetime.now().replace(microsecond=0).isoformat()

def _read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")

def _write_text_safe(path: Path, content: str, force: bool) -> Tuple[Path, str]:
    """
    Returns (written_path, mode) where mode in {"overwritten","created","newfile"}.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and not force:
        existing = _read_text(path)
        if AUTO_MARKER not in existing:
            new_path = path.with_suffix(path.suffix + ".new")
            new_path.write_text(content, encoding="utf-8")
            return new_path, "newfile"
    mode = "overwritten" if path.exists() else "created"
    path.write_text(content, encoding="utf-8")
    return path, mode

def _try_import_yaml():
    try:
        import yaml  # type: ignore
        return yaml
    except Exception:
        return None

def _yaml_dump(data: Any) -> str:
    yaml = _try_import_yaml()
    if yaml is None:
        # Minimal YAML-ish output (good enough for simple structures)
        return _miniyaml_dump(data)
    return yaml.safe_dump(data, sort_keys=False, allow_unicode=True)

def _miniyaml_dump(obj: Any, indent: int = 0) -> str:
    sp = "  " * indent
    if isinstance(obj, dict):
        out = []
        for k, v in obj.items():
            if isinstance(v, (dict, list)):
                out.append(f"{sp}{k}:")
                out.append(_miniyaml_dump(v, indent + 1))
            else:
                out.append(f"{sp}{k}: { _miniyaml_scalar(v) }")
        return "\n".join(out) + "\n"
    if isinstance(obj, list):
        out = []
        for it in obj:
            if isinstance(it, (dict, list)):
                out.append(f"{sp}-")
                out.append(_miniyaml_dump(it, indent + 1).rstrip("\n"))
            else:
                out.append(f"{sp}- { _miniyaml_scalar(it) }")
        return "\n".join(out) + "\n"
    return f"{sp}{_miniyaml_scalar(obj)}\n"

def _miniyaml_scalar(v: Any) -> str:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    s = str(v)
    # quote if needed
    if re.search(r"[:#\n\r\t]", s) or s.strip() != s or s == "" or s.lower() in {"null","true","false"}:
        s = s.replace('"', '\\"')
        return f"\"{s}\""
    return s

def _repo_root_from_script(script_path: Path) -> Path:
    # scripts/ is inside repo root_IA/
    return script_path.resolve().parent.parent

def _load_yaml_file(path: Path) -> Optional[dict]:
    yaml = _try_import_yaml()
    if yaml is None:
        return None
    try:
        return yaml.safe_load(path.read_text(encoding="utf-8"))
    except Exception:
        return None

def _infer_team_id_from_filename(team_file: Path) -> str:
    # TEAM__IAHQ.yaml -> IAHQ
    m = re.match(r"TEAM__([A-Za-z0-9_-]+)\.ya?ml$", team_file.name)
    if m:
        return m.group(1)
    return team_file.stem.replace("TEAM__", "")

def rebuild_teams_index(repo: Path, force: bool) -> List[str]:
    teams_dir = repo / "10_TEAMS"
    out_path = teams_dir / "teams.yaml"
    teams: List[Dict[str, Any]] = []

    for tf in sorted(teams_dir.glob("TEAM__*.y*ml")):
        data = _load_yaml_file(tf)
        team_id = _infer_team_id_from_filename(tf)
        name = team_id
        status = "active"
        purpose = ""
        if isinstance(data, dict):
            # best-effort extraction
            name = data.get("name") or data.get("team_name") or name
            status = data.get("status") or status
            purpose = data.get("purpose") or data.get("description") or ""
            team_id = data.get("team_id") or data.get("id") or team_id

        teams.append({
            "team_id": team_id,
            "name": name,
            "status": status,
            "purpose": purpose,
            "file": str(tf.relative_to(repo)).replace("\\", "/"),
        })

    payload = {
        "meta": {
            "marker": AUTO_MARKER,
            "generated_at": _now_iso(),
            "repo": "root_IA",
            "version": 1,
        },
        "teams": teams,
    }

    content = _yaml_dump(payload)
    written, mode = _write_text_safe(out_path, content, force)
    return [f"[teams] {mode}: {written} (teams={len(teams)})"]

def _agent_dirs(repo: Path) -> List[Path]:
    base = repo / "20_AGENTS"
    if not base.exists():
        return []
    out: List[Path] = []
    for team_dir in sorted([p for p in base.iterdir() if p.is_dir()]):
        for agent_dir in sorted([p for p in team_dir.iterdir() if p.is_dir()]):
            out.append(agent_dir)
    return out

def _infer_agent_name(actor_id: str) -> str:
    # META-OrchestrateurCentral -> Orchestrateur Central
    s = actor_id.split("-")[-1]
    s = re.sub(r"([a-z])([A-Z])", r"\1 \2", s)
    s = s.replace("_", " ").strip()
    return s if s else actor_id

def _read_prompt_title(agent_dir: Path) -> str:
    p = agent_dir / "prompt.md"
    if not p.exists():
        return ""
    try:
        first = p.read_text(encoding="utf-8").splitlines()[:10]
        for line in first:
            line = line.strip()
            if line.startswith("#"):
                return line.lstrip("#").strip()
    except Exception:
        pass
    return ""

def ensure_agent_yaml(repo: Path, force: bool) -> List[str]:
    logs: List[str] = []
    for agent_dir in _agent_dirs(repo):
        agent_yaml = agent_dir / "agent.yaml"
        team_id = agent_dir.parent.name
        actor_id = agent_dir.name

        existing = _load_yaml_file(agent_yaml) if agent_yaml.exists() else None
        if isinstance(existing, dict) and not force:
            # keep existing, but ensure minimal fields
            changed = False
            for k, v in {
                "actor_id": actor_id,
                "team_id": existing.get("team_id") or team_id,
                "status": existing.get("status") or "active",
            }.items():
                if existing.get(k) != v:
                    existing[k] = v
                    changed = True
            if changed and AUTO_MARKER in (agent_yaml.read_text(encoding="utf-8", errors="ignore")):
                content = _yaml_dump(existing)
                written, mode = _write_text_safe(agent_yaml, content, force=True)
                logs.append(f"[agent.yaml] {mode}: {written}")
            continue

        title = _read_prompt_title(agent_dir)
        name = title or _infer_agent_name(actor_id)
        agent_obj = {
            "meta": {"marker": AUTO_MARKER, "generated_at": _now_iso(), "version": 1},
            "actor_id": actor_id,
            "team_id": team_id,
            "name": name,
            "status": "active",
            "description": "",
            "artifacts": {
                "prompt": str((agent_dir / "prompt.md").relative_to(repo)).replace("\\", "/") if (agent_dir / "prompt.md").exists() else "",
                "contract": str((agent_dir / "contract.yaml").relative_to(repo)).replace("\\", "/") if (agent_dir / "contract.yaml").exists() else "",
                "readme": str((agent_dir / "README.md").relative_to(repo)).replace("\\", "/") if (agent_dir / "README.md").exists() else "",
            },
        }
        content = _yaml_dump(agent_obj)
        written, mode = _write_text_safe(agent_yaml, content, force)
        logs.append(f"[agent.yaml] {mode}: {written}")
    return logs

def rebuild_agents_inventory(repo: Path, force: bool) -> List[str]:
    inv: List[Dict[str, Any]] = []
    for agent_dir in _agent_dirs(repo):
        agent_yaml = agent_dir / "agent.yaml"
        data = _load_yaml_file(agent_yaml) if agent_yaml.exists() else None
        actor_id = agent_dir.name
        team_id = agent_dir.parent.name
        name = _infer_agent_name(actor_id)
        status = "active"
        if isinstance(data, dict):
            actor_id = data.get("actor_id") or actor_id
            team_id = data.get("team_id") or team_id
            name = data.get("name") or name
            status = data.get("status") or status
        inv.append({
            "actor_id": actor_id,
            "team_id": team_id,
            "name": name,
            "status": status,
            "path": str(agent_dir.relative_to(repo)).replace("\\", "/"),
        })

    payload = {
        "meta": {"marker": AUTO_MARKER, "generated_at": _now_iso(), "version": 1},
        "agents": sorted(inv, key=lambda x: (x["team_id"], x["actor_id"])),
    }

    out_path = repo / "00_INDEX" / "agents.yaml"
    content = _yaml_dump(payload)
    written, mode = _write_text_safe(out_path, content, force)
    return [f"[agents] {mode}: {written} (agents={len(inv)})"]

def rebuild_policies_index(repo: Path, force: bool) -> List[str]:
    policies_dir = repo / "50_POLICIES"
    out_path = policies_dir / "POLICIES__INDEX.md"
    items: List[Tuple[str, str]] = []  # (path, title)
    for p in sorted(policies_dir.glob("*.y*ml")):
        title = p.stem
        # Try to read a 'name' or first comment line
        try:
            txt = p.read_text(encoding="utf-8")
            m = re.search(r"^\s*name\s*:\s*(.+)\s*$", txt, flags=re.MULTILINE)
            if m:
                title = m.group(1).strip().strip('"').strip("'")
            else:
                # first comment line
                for line in txt.splitlines()[:20]:
                    if line.strip().startswith("#"):
                        title = line.strip("#").strip() or title
                        break
        except Exception:
            pass
        items.append((str(p.relative_to(repo)).replace("\\", "/"), title))

    lines = []
    lines.append(f"# POLICIES — Index")
    lines.append("")
    lines.append(f"> {AUTO_MARKER}")
    lines.append(f"> Generated at: {_now_iso()}")
    lines.append("")
    lines.append("## Liste des policies")
    lines.append("")
    for path, title in items:
        lines.append(f"- **{title}** — `{path}`")
    lines.append("")
    lines.append("## Règle d’or")
    lines.append("")
    lines.append("- Toute équipe (META/IAHQ/OPS/IT/...) doit respecter ces policies dans les sorties, playbooks et prompts.")
    lines.append("- Si une policy change, relancer `scripts/rebuild_indexes.ps1` pour mettre à jour les index/bundles.")
    lines.append("")
    content = "\n".join(lines)

    written, mode = _write_text_safe(out_path, content, force)
    return [f"[policies] {mode}: {written} (policies={len(items)})"]

def _bundle_core_text(repo: Path) -> str:
    # Generate a concise but useful core context referencing files.
    return "\n".join([
        "# CONTEXT — CORE (root_IA)",
        "",
        f"> {AUTO_MARKER}",
        f"> Generated at: {_now_iso()}",
        "",
        "## Sources de vérité (références)",
        "",
        "- Organisation (équipes) : `10_TEAMS/teams.yaml` + fichiers `10_TEAMS/TEAM__*.yaml`",
        "- Inventaire agents : `00_INDEX/agents.yaml` + dossiers `20_AGENTS/**/`",
        "- Routage : `80_MACHINES/hub_routing.yaml`",
        "- Playbooks : `40_RUNBOOKS/playbooks.yaml`",
        "- Policies : `50_POLICIES/POLICIES__INDEX.md` + `50_POLICIES/*.yaml`",
        "- Schémas : `SCHEMAS/*.json` (copie distributable : `70_INTEGRATION_PACKAGES/SCHEMAS/`)",
        "",
        "## Principes",
        "",
        "- **root_IA = source de vérité** (réutiliser les templates/runbooks, éviter les variantes non conformes).",
        "- **MO** (Master Orchestrator) = point d’entrée et mémoire système; **MO2** = QA/recette et cohérence.",
        "- Ajouter un agent via : `40_RUNBOOKS/RUNBOOKS_MD/RUNBOOK__ADD_AGENT.md`",
        "",
    ])

def _bundle_team_text(team: str) -> str:
    if team == "META":
        return "\n".join([
            "# INDEX — META (Factory)",
            "",
            "## Ce que META produit",
            "- Agents conformes (schema + policies)",
            "- Teams + playbooks (standard root_IA)",
            "- Optimisation prompts + gouvernance création",
            "",
            "## Fichiers essentiels",
            "- Templates : `90_KNOWLEDGE/TEMPLATES/TEMPLATE__AGENT.md`, `.../TEMPLATE__PLAYBOOK.md`",
            "- Runbooks : `40_RUNBOOKS/RUNBOOKS_MD/RUNBOOK__CREATE_TEAM.md`, `...__CREATE_PLAYBOOK.md`, `...__PROMPT_REVIEW_CHECKLIST.md`",
            "- Schéma agent : `SCHEMAS/agent.schema.json`",
        ])
    if team == "IAHQ":
        return "\n".join([
            "# INDEX — IAHQ (Delivery)",
            "",
            "## Ce que IAHQ produit",
            "- Diagnostic / As-Is / To-Be",
            "- Risques & qualité (gouvernance IA)",
            "- Business case / ROI prudent",
            "- Plan 30-60-90 jours",
            "",
            "## Fichiers essentiels",
            "- Templates : `90_KNOWLEDGE/TEMPLATES/TEMPLATE__PROPOSITION_IAHQ.md`, `.../TEMPLATE__30_60_90.md`",
            "- ROI : `90_KNOWLEDGE/ROI/ROI_ASSUMPTIONS.md`, `.../ROI_SCENARIOS.md`",
            "- Policies : `50_POLICIES/*`",
        ])
    if team == "OPS":
        return "\n".join([
            "# INDEX — OPS (Control plane / Exécution)",
            "",
            "## Ce que OPS gère",
            "- Routage intents → acteurs",
            "- Exécution playbooks + dossiers",
            "- Observabilité / QA gates via MO2",
            "",
            "## Fichiers essentiels",
            "- Routage : `80_MACHINES/hub_routing.yaml`",
            "- Playbooks : `40_RUNBOOKS/playbooks.yaml`",
            "- Runbooks MO : `40_RUNBOOKS/RUNBOOKS_MD/RUNBOOK__MO_CONTROL_PLANE.md`",
        ])
    return f"# INDEX — {team}\n\n(aucun contenu spécifique)\n"

def rebuild_bundles(repo: Path, force: bool) -> List[str]:
    logs: List[str] = []
    knowledge = repo / "90_KNOWLEDGE"
    bundles_dir = knowledge / "BUNDLES"
    bundles_dir.mkdir(parents=True, exist_ok=True)

    # core
    core_path = knowledge / "CONTEXT__CORE.md"
    core_content = _bundle_core_text(repo)
    p, mode = _write_text_safe(core_path, core_content, force)
    logs.append(f"[core] {mode}: {p}")

    # per-team indexes
    for team in ["META", "IAHQ", "OPS"]:
        idx_path = knowledge / f"INDEX__{team}.md"
        idx_content = "\n".join([
            _bundle_team_text(team),
            "",
            "## Références complémentaires",
            "- Équipes : `10_TEAMS/teams.yaml`",
            "- Agents : `00_INDEX/agents.yaml`",
            "- Policies : `50_POLICIES/POLICIES__INDEX.md`",
            "",
        ])
        p, mode = _write_text_safe(idx_path, idx_content, force)
        logs.append(f"[index:{team}] {mode}: {p}")

        bundle_path = bundles_dir / f"BUNDLE__{team}_UPLOAD.md"
        bundle_content = "\n".join([
            f"# BUNDLE — {team} (upload)",
            "",
            f"> {AUTO_MARKER}",
            f"> Generated at: {_now_iso()}",
            "",
            "## CORE",
            "",
            core_content,
            "",
            "## INDEX",
            "",
            idx_content,
            "",
            "## Pointeurs rapides",
            "",
            "- Teams : `10_TEAMS/teams.yaml`",
            "- Agents : `00_INDEX/agents.yaml`",
            "- Routage : `80_MACHINES/hub_routing.yaml`",
            "- Playbooks : `40_RUNBOOKS/playbooks.yaml`",
            "- Policies : `50_POLICIES/POLICIES__INDEX.md`",
            "",
        ])
        p, mode = _write_text_safe(bundle_path, bundle_content, force)
        logs.append(f"[bundle:{team}] {mode}: {p}")

    return logs

def mirror_schemas_into_integration_packages(repo: Path, force: bool) -> List[str]:
    """
    Copies SCHEMAS/*.json into 70_INTEGRATION_PACKAGES/SCHEMAS for distribution.
    """
    src = repo / "SCHEMAS"
    dst = repo / "70_INTEGRATION_PACKAGES" / "SCHEMAS"
    logs: List[str] = []
    if not src.exists():
        return ["[schemas] SKIP: SCHEMAS/ not found"]
    dst.mkdir(parents=True, exist_ok=True)
    for f in sorted(src.glob("*.json")):
        target = dst / f.name
        if target.exists() and not force:
            continue
        target.write_text(f.read_text(encoding="utf-8"), encoding="utf-8")
        logs.append(f"[schemas] copied: {target.relative_to(repo)}")
    return logs

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", help="Chemin vers le dossier root_IA", default=None)
    ap.add_argument("--force", help="Écrase même les fichiers non auto-générés", action="store_true")
    ap.add_argument("--bundles", help="Reconstruit CONTEXT__CORE + INDEX + BUNDLES", action="store_true")
    ap.add_argument("--mirror-schemas", help="Copie SCHEMAS/*.json → 70_INTEGRATION_PACKAGES/SCHEMAS/", action="store_true")
    args = ap.parse_args()

    script_path = Path(__file__)
    repo = Path(args.root).resolve() if args.root else _repo_root_from_script(script_path)

    if not repo.exists():
        print(f"ERROR: repo root not found: {repo}", file=sys.stderr)
        return 2

    logs: List[str] = []
    logs += rebuild_teams_index(repo, force=args.force)
    logs += ensure_agent_yaml(repo, force=args.force)
    logs += rebuild_agents_inventory(repo, force=args.force)
    logs += rebuild_policies_index(repo, force=args.force)

    if args.mirror_schemas:
        logs += mirror_schemas_into_integration_packages(repo, force=args.force)

    if args.bundles:
        logs += rebuild_bundles(repo, force=args.force)

    print("\n".join(logs))
    print("\nDONE.")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
